name: Build Inflation Calculator

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: python-version: '3.x'
      - run: |
          pip install --upgrade pip
          pip install pyinstaller
      - run: |
          pyinstaller --onefile --windowed \
            --icon=inflation_icon.ico \
            inflation_gui_calculator.py
      - uses: actions/upload-artifact@v3
        with:
          name: InflationCalculator-Windows
          path: dist/inflation_gui_calculator.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: python-version: '3.x'
      - run: |
          pip3 install --upgrade pip
          pip3 install pyinstaller
      - run: |
          pyinstaller --onefile --windowed \
            --icon=inflation_icon.icns \
            inflation_gui_calculator.py
      - uses: actions/upload-artifact@v3
        with:
          name: InflationCalculator-macOS
          path: dist/inflation_gui_calculator.app
